//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterSalesDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGLUONGTL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANGLUONGTL()
        {
            this.CT_BANGLUONGTL = new HashSet<CT_BANGLUONGTL>();
        }
    
        public string id { get; set; }
        public string MaKeToan { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> Thang { get; set; }
        public string MaPhong { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BANGLUONGTL> CT_BANGLUONGTL { get; set; }
    }
}
