//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterSalesDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BANGLUONGTL
    {
        public string id { get; set; }
        public string MaLuongTL { get; set; }
        public string MaNV { get; set; }
        public Nullable<decimal> LuongCB { get; set; }
        public Nullable<decimal> TienThuong { get; set; }
        public Nullable<decimal> LuongLamThem { get; set; }
        public Nullable<decimal> PhuCap { get; set; }
        public Nullable<decimal> TongLuong { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual BANGLUONGTL BANGLUONGTL { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
