//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterSalesDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIAKYNANG
    {
        public string id { get; set; }
        public string MaNV { get; set; }
        public string MaKyNang { get; set; }
        public string LoaiDanhGia { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual KYNANG KYNANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
